export const MESSAGE = {
  USER_EXISTS: 'User already exists',
  USER_CREATED: 'User created successfully',
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_NICKNAME_FOUND: 'User nickname fetched successfully',
  USER_FOUND: 'User fetched successfully',
  USER_NICKNAME_NOT_FOUND: 'User nickname not found',
  USER_NICKNAME_UPDATED: 'User nickname updated',
  USER_NOT_FOUND: 'User not found',
  MISSION_FOUND: 'Mission fetched successfully',
  MISSION_NOT_FOUND: 'Mission not found',
  USER_MISSION_CREATED: 'User Mission created successfully',
  USER_MISSION_NOT_CREATED: 'User Mission not created',
  USER_MISSION_NOT_FOUND: 'User Mission not found',
  USER_MISSION_FOUND: 'User Mission found',
  USER_MISSION_SELECTED: 'User Mission already selected',
  USER_MISSION_NOT_UPDATED: 'User Mission not updated',
  USER_MISSION_UPDATED: 'User Mission updated',
  USER_MISSION_NOT_DELETED: 'User Mission not deleted',
  USER_MISSION_DELETED: 'User Mission deleted',
};
